export default {
    FETCH_USER_LIST_REQUEST: '@@app/FETCH_USER_LIST_REQUEST',
    FETCH_USER_LIST_SUCCESS: '@@app/FETCH_USER_LIST_SUCCESS',
    FETCH_USER_LIST_ERROR: '@@app/FETCH_USER_LIST_ERROR'
};
