export default {
    INIT_APPLICATION_START: '@@app/INIT_APPLICATION_START',
    INIT_APPLICATION_SUCCESS: '@@app/INIT_APPLICATION_SUCCESS',
    INIT_APPLICATION_ERROR: '@@app/INIT_APPLICATION_ERROR'
};
